Repository widdix/aws-cf-templates, pull requests merged in 2020-04, with the labels that each got.

#423 [New Template] operations/alb-access-logs-anonymizer - Anonymize ALB Access Log
  operations/alb-access-logs-anonymizer.yaml
Labels: Work in Progress

#410 [Improvement] vpc/vpc-*-legacy - Add InternetGateway export (breaking change)
  test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC2AZsLegacy.java
  test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC3AZsLegacy.java
  test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC4AZsLegacy.java
  vpc/vpc-2azs-legacy.yaml
  vpc/vpc-3azs-legacy.yaml
  vpc/vpc-4azs-legacy.yaml
Labels: Breaking Change

#426 [Improvement] * - IPv6 support for subnets, public load balancers, and CloudFront (breaking change)
  docs/img/vpc-2azs.png
  docs/img/vpc-3azs.png
  docs/img/vpc-4azs.png
  docs/vpc.md
  ecs/cluster.yaml
  ecs/service-cluster-alb.yaml
  ecs/service-dedicated-alb.yaml
  fargate/cluster.yaml
  fargate/service-cluster-alb.yaml
  fargate/service-dedicated-alb.yaml
  jenkins/jenkins2-ha-agents.yaml
  jenkins/jenkins2-ha.yaml
  security/auth-proxy-ha-github-orga.yaml
  static-website/static-website.yaml
  vpc/vpc-2azs-legacy.yaml
  vpc/vpc-2azs.yaml
  vpc/vpc-3azs-legacy.yaml
  vpc/vpc-3azs.yaml
  vpc/vpc-4azs-legacy.yaml
  vpc/vpc-4azs.yaml
  wordpress/wordpress-ha-aurora.yaml
  wordpress/wordpress-ha.yaml
Labels: Breaking Change

#428 [Improvement] state/rds-postgres - Add support for parameter and option groups
  state/rds-postgres.yaml
Labels: Enhancement
